Add Astronomy Picture of the Day bot command
flan6/FlanBot pull request #1
Opened 2022-06-14 16:28 UTC by LuigiAzevedo

!NASA

2022-06-14 16:32 UTC, LuigiAzevedo commented
Add Astronomy Picture of the Day bot command

2022-06-14 16:49 UTC, flan6 requested changes
Sobre o retorno do nasa picture vou checar, der repente rola de retornar o json direto.

2022-06-14 16:49 UTC, flan6 commented on .gitignore
> +.idea/workspace.xml
os ignores de IDE vc tem q por num ignore global do seu pc. 

Imagina todo projeto ter q por ignore de um monte de IDE diferente de todo mundo q trabalhar nele.

2022-06-14 16:49 UTC, flan6 commented on .gitignore
> +.env_sample
o sample nao pode ser ignorado pq é o exemplo pra criarem o proprio env

2022-06-14 16:49 UTC, flan6 commented on helpers.py
> +from datetime import datetime
pode renomear pra nasa.py e fazer uma classe, desse modo pode adicionar novos metodos no futuro. como buscar imagem aleatoria do hubble

2022-06-14 16:50 UTC, flan6 commented
De repente seria uma boa tbm fazer unit tests se vc quiser praticar

2022-06-14 21:03 UTC, LuigiAzevedo commented
Alterações solicitadas foram feitas.

2022-06-15 23:28 UTC, flan6 approved these changes

2022-06-15 23:29 UTC, merged